In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
tips = px.data.tips()
iris = px.data.iris()
gap = px.data.gapminder()

In [3]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [4]:
temp_df=gap[gap['year'] == 2007]

In [5]:
trace1 = go.Scatter(x=temp_df['lifeExp'],y=temp_df['gdpPercap'],mode = 'markers')
trace2 = go.Scatter(x = [0,1,2] , y=[0,90,3000] , mode='lines')

data = [trace1,trace2]

Layout = go.Layout(title='life Exp Vs gdp per capita for 2007',xaxis={'title':'Life Exp'},yaxis={'title':'GDP'})
fig = go.Figure(data,Layout)

fig.show()

In [6]:
px.scatter(temp_df,x='lifeExp',y='gdpPercap',color='continent',size = 'pop',size_max=100,hover_name = 'country')

In [7]:
#plot animation of the above curve ont he basic of year
px.scatter(gap,x='lifeExp',y='gdpPercap',
           color='continent',size = 'pop',size_max=100,
           hover_name = 'country',
           range_x = [20,95],
           animation_frame='year',animation_group='country')

In [8]:
#line plot
#plot india pop line plot
temp_df=gap[gap['country']=='India']
px.line(temp_df,x='year',y='pop')

In [9]:
#plot india china pak line plot
temp_df=gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='lifeExp')
temp_df

country     China   India  Pakistan
year
1952     44.00000  37.373    43.436
1957     50.54896  40.249    45.557
1962     44.50136  43.605    47.670
1967     58.38112  47.193    49.800
1972     63.11888  50.651    51.929
1977     63.96736  54.208    54.043
1982     65.52500  56.596    56.158
1987     67.27400  58.553    58.245
1992     68.69000  60.223    60.838
1997     70.42600  61.765    61.818
2002     72.02800  62.879    63.610
2007     72.96100  64.698    65.483

In [10]:
px.line(temp_df,x=temp_df.index,y=temp_df.columns)

In [11]:
#bar chart
#india's pop over the years
temp_df = gap[gap['country'] == 'India']
px.bar(temp_df,x='year',y='pop')

In [12]:
#pop comp of 3 countries
temp_df = gap[gap['country'].isin(['India','China','Pakistan'])].pivot(index='year',columns='country',values='pop')
temp_df

country       China       India   Pakistan
year
1952      556263527   372000000   41346560
1957      637408000   409000000   46679944
1962      665770000   454000000   53100671
1967      754550000   506000000   60641899
1972      862030000   567000000   69325921
1977      943455000   634000000   78152686
1982     1000281000   708000000   91462088
1987     1084035000   788000000  105186881
1992     1164970000   872000000  120065004
1997     1230075000   959000000  135564834
2002     1280400000  1034172547  153403524
2007     1318683096  1110396331  169270617

In [13]:
px.bar(temp_df,x=temp_df.index,y=temp_df.columns,barmode='group',log_y=True,text_auto=True)#grouped bar graph

In [14]:
#stacked bar chart
#pop contribution per country to a contients pop stacked for a particular year(2007)
temp_df = gap[gap['year']==2007]
px.bar(temp_df,x='continent',y='pop',color='country',log_y=True)

In [15]:
#barchart animation
px.bar(gap,x='continent',y='pop',color='continent',animation_frame='year',animation_group='country',range_y=[0,4000000000])

In [16]:
#histogram
#plot histogram of life exppt of all countries in 2007 -> nbins -> text_auto
temp_df = gap[gap['year']==2007]
px.histogram(temp_df,x='lifeExp',text_auto=True)

In [17]:
#plot histogram of sepal length of all species
px.histogram(iris,x='sepal_length',color='species',nbins=30,text_auto=True)

In [19]:
#pie -> values -> names
#find the pie chartgs of pop of europeans countries in 2007
temp_df=gap[(gap['year'] == 2007) & (gap['continent'] == 'Europe')]
px.pie(temp_df,values='pop',names='country')

In [21]:
#plot pie chart of world pop in 1952 contient wise -> -> explode(pull)
temp_df = gap[gap['year']== 1952].groupby('continent')['pop'].sum().reset_index()
temp_df
px.pie(temp_df,values='pop',names='continent')

In [22]:
#sunbrust plot -> sunbrust plots visualise hierarchical data spanning outwards radially from root to leave. -> color
#path -> [], values

temp_df = gap[gap['year'] == 2007]
px.sunburst(temp_df,path=['continent','country'],values='pop',color='lifeExp')

In [23]:
px.sunburst(tips,path={'sex','smoker','day','time'},values='total_bill',color='size')

In [24]:
#treemap
tmep_df = gap[gap['year'] == 2007]
px.treemap(temp_df,path=[px.Constant('World'),'continent','country'],values='pop',color='lifeExp')

In [25]:
#heatmap -> find heatmap of all continents with year on avg life exp
#temp_df = tips.pivot_table(index='day',columns='sex',values='total_bill',aggfunc='sum')
temp_df = gap.pivot_table(index='year',columns='continent',values='lifeExp',aggfunc='mean')
px.imshow(temp_df)

In [26]:
#3D scatter plot
#plot a 3d scatter plot of all theh country data for 2007
temp_df = gap[gap['year'] == 2007]
px.scatter_3d(temp_df,x='lifeExp',y='pop',z='gdpPercap',log_y=True,color='continent',hover_name='country')

In [27]:
px.scatter_3d(iris,x='sepal_length',y='sepal_width',z='petal_length',color='species')

In [29]:
fig = px.scatter_matrix(
    iris,
    dimensions=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'],
    color='species'
)

fig.update_layout(
    width=900,
    height=900
)

fig.show()